<?php
/**
 * Replacement of legacy dealer ledger
 *
 * @file
 * @date 2014-06-19
 * @author Samuel J. Lawson <slawson@mooreheadcomm.com>
 */

namespace DealerLedger {

    /**
     * Will build the block content function name and call it.
     *
     * @param string $blockName
     *
     * @return array
     */
    function get_block_content($blockName)
    {
        require_once('includes/blocks/' . $blockName . '.php');
        return call_user_func(__NAMESPACE__ . '\\_' . $blockName);
    }

    /**
     * Gets the name of the module
     *
     * @return string Name of the module
     */
    function get_module_name()
    {
        return basename(__FILE__, '.module');
    }

    /**
     * Gets the path of the module
     *
     * @return string Path relative to DRUPAL_ROOT.
     */
    function get_module_path()
    {
        // Must be relative to be used with Drupal functions
        return drupal_get_path('module', get_module_name());
    }

    /**
     * Gets the standardized name for the page callback
     *
     * @param string $pageCallback
     *
     * @return string
     */
    function get_page_callback_name($pageCallback)
    {
        return __NAMESPACE__ . '\\' . $pageCallback;
    }

    /**
     * Gets the standardized name for the page callback filename
     *
     * @param string $directory Relative path to the module path without leading or trailing slash
     * @param string $pageCallback
     *
     * @return string
     */
    function get_page_callback_filename($directory, $pageCallback)
    {
        return $directory . DIRECTORY_SEPARATOR . $pageCallback . '.inc.php';
    }

    /**
     * Gets the standardized name for a page permission
     *
     * @param  string  $page
     * @param  boolean $inArray
     * @return string
     */
    function get_permission_name($page)
    {
        return 'access ' . get_module_name() . ' ' . $page;
    }

    /**
     * Gets the standardized theme callback
     */
    function get_theme_callback_name()
    {
        return __NAMESPACE__ . '\theme_callback';
    }

    /**
     * Gets the standardized name for a page theme
     *
     * @param string $theme
     * @return string
     */
    function get_theme_name($theme)
    {
        return get_module_name() . '_' . $theme;
    }

    /**
     * Gets the username in all circumstances.
     *
     * @return string
     */
    function get_username()
    {
        global $user;
        if (isset($user->name)) {
            return $user->name;
        }
        else if (isset($user->uid) && ($user->uid === 0)) {
            return 'anonymous';
        }

        return 'unknown';
    }

    /**
     * This method is called first before every page request by each include file.
     */
    function load_resources()
    {
        require __DIR__ . '/vendor/autoload.php';
        mhc_error_and_exception_handler_register('dealer_ledger', 'slawson@mooreheadcomm.com');
    }

    /**
     * Used in hook_menu() as a theme callback.
     *
     * @return string
     */
    function theme_callback()
    {
        return 'dealer_ledger';
    }
}

namespace {

    /**
     * Implementation of hook_help().
     *
     * @param string $path
     * @param string $arg
     */
    function dealer_ledger_help($path, $arg)
    {
        switch ($path) {
        case 'admin/help#dealer_ledger':
            return t('<p>Account export cron and internal ui for dealer ledger.</p>');
        }
    }

    /**
     * Implementation of hook_menu().
     *
     * @return array
     */
    function dealer_ledger_menu()
    {
        return array(
            // New menu items are appended here.
            'app/dealer_ledger/export' => array(
                'title' => 'Dealer Ledger Account Export',
                'description' => '',
                'access callback' => 'mhc_acl_check_access',
                'access arguments' => array(DealerLedger\get_permission_name('dealer_ledger_dealer_ledger_account_exports')),
                'file' => DealerLedger\get_page_callback_filename('includes/pages', 'dealer_ledger_dealer_ledger_account_exports'),
                'menu_name' => 'main-menu',
                'page callback' => DealerLedger\get_page_callback_name('_dealer_ledger_dealer_ledger_account_exports'),
                'type' => MENU_NORMAL_ITEM,
            ),
            'app/dealer_ledger/crons/account/%' => array(
                'title' => 'dealer ledger account exports',
                'description' => 'Cron page for dealer ledger account exports',
                'access callback' => 'mhc_acl_check_access',
                'access arguments' => array(DealerLedger\get_permission_name('dealer_ledger_cron_dealer_ledger_account_exports')),
                'file' => DealerLedger\get_page_callback_filename('includes/crons', 'dealer_ledger_cron_dealer_ledger_account_exports'),
                'menu_name' => 'main-menu',
                'page arguments' => array(4),
                'page callback' => DealerLedger\get_page_callback_name('_dealer_ledger_cron_dealer_ledger_account_exports'),
                'type' => MENU_CALLBACK,
                ),
        );
    }

    /**
     * Implements hook_permission()
     *
     * Permissions name strings follow the pattern:
     *     "access <moduleName> <includeFileBasename>"
     * Example:
     *     module name = dealer_ledger, page include file = new_page.inc.php
     *     therefore permission name = "access dealer_ledger new_page"
     */
    function dealer_ledger_permission()
    {
        return array(
            // New permissions are appended here.
            DealerLedger\get_permission_name('dealer_ledger_dealer_ledger_account_exports') => array(
                'title' => 'Access to the Dealer Ledger Account Exports page.'
            ),
            DealerLedger\get_permission_name('dealer_ledger_cron_dealer_ledger_account_exports') => array(
                'title' => 'Access to the dealer ledger account exports cron page.'
            ),
        );
    }

    /**
     * This is an implementation of hook_theme().
     *
     * @param array  $existing
     * @param string $type
     * @param string $theme
     * @param string $path
     *
     * @return array
     */
    function dealer_ledger_theme($existing, $type, $theme, $path)
    {
        return array(
            // New themes are appended here.
            'dealer_ledger_dealer_ledger_account_exports_page' => array(
                'path' => $path . '/templates',
                'template' => 'dealer_ledger_dealer_ledger_account_exports',
                'variables' => array(
                    'dealerLedgerAccountExportsForm' => null,
                )
            ),
        );
    }

    // Miscellaneous hooks are appended here.
}
